---
- hosts: [ dev ]
  remote_user: ubuntu
  become: yes
  tasks:
    - name: install system dependencies
      apt: pkg={{item}} state=present
      with_items: [ nginx, postgresql, nodejs, nodejs-legacy, npm ]


    - name: ensure base services are running
      service: name={{item}} state=started enabled=yes
      with_items: [ nginx ]

    - name: install nginx basic auth password file
      template: src=passwd dest=/etc/nginx/passwd
      notify:
        - restart nginx

    - name: install nginx.conf
      template: src=nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
