---
- hosts: [ dev ]
  remote_user: ubuntu
  become: yes

  roles:
    - weareinteractive.pm2

  vars:
    pm2_service_name: pm2
    pm2_apps:
      - run: /srv/app.json
        path: /srv/checkout/tradenomiitti
        cmd: start
    pm2_user: ubuntu
